from django.urls import path
from django.views.generic import RedirectView

from posapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('waiter', RedirectView.as_view(url='waiter/tabs'), name='waiter'),
    path('waiter/tabs', views.Waiter.Tabs.as_view(), name='waiter/tabs'),
    path('waiter/tabs/<uuid:id>', views.Waiter.Tabs.Tab.as_view(), name='waiter/tabs/tab'),
    path('waiter/orders', views.Waiter.Orders.as_view(), name='waiter/orders'),
    path('waiter/orders/<uuid:id>', views.Waiter.Orders.Order.as_view(), name='waiter/orders/order'),
    path('waiter/orders/<uuid:id>/bump/<int:count>', views.Waiter.Orders.Order.Bump.as_view(),
         name='waiter/orders/order/bump'),
    path('waiter/orders/<uuid:id>/requestVoid', views.Waiter.Orders.Order.RequestVoid.as_view(),
         name='waiter/orders/order/requestVoid'),
    path('waiter/orders/<uuid:id>/void', views.Waiter.Orders.Order.Void.as_view(), name='waiter/orders/order/void'),
    path('waiter/orders/<uuid:id>/authenticateAndVoid', views.Waiter.Orders.Order.AuthenticateAndVoid.as_view(),
         name='waiter/orders/order/authenticateAndVoid'),
    path('manager', RedirectView.as_view(url="manager/users"), name='manager'),
    path('manager/users', views.Manager.Users.as_view(), name='manager/users'),
    path('manager/users/create', views.Manager.Users.Create.as_view(), name='manager/users/create'),
    path('manager/users/<str:username>', views.Manager.Users.User.as_view(), name='manager/users/user'),
    path('manager/tills', views.Manager.Tills.as_view(), name='manager/tills'),
    path('manager/tills/assign', views.Manager.Tills.Assign.as_view(), name='manager/tills/assign'),
    path('manager/tills/<uuid:id>', views.Manager.Tills.Till.as_view(), name='manager/tills/till'),
    path('manager/tills/<uuid:id>/stop', views.Manager.Tills.Till.Stop.as_view(), name='manager/tills/till/stop'),
    path('manager/tills/<uuid:id>/count', views.Manager.Tills.Till.Count.as_view(), name='manager/tills/till/count'),
    path('manager/tills/<uuid:id>/close', views.Manager.Tills.Till.Close.as_view(), name='manager/tills/till/close'),
    path('manager/tills/<uuid:id>/edit', views.Manager.Tills.Till.Edit.as_view(), name='manager/tills/till/edit'),
    path('manager/voidrequests', views.Manager.VoidRequests.as_view(), name='manager/voidrequests'),
    path('manager/voidrequests/<uuid:id>/<str:resolution>', views.Manager.VoidRequests.Resolve.as_view(),
         name='manager/voidrequests/resolve'),
    path('director', RedirectView.as_view(url="director/finance"), name='director'),
    path('director/finance', RedirectView.as_view(url="director/finance/currencies"), name='director/finance'),
    path('director/finance/currencies', views.Admin.Finance.Currencies.as_view(), name='director/finance/currencies'),
    path('director/finance/methods', views.Admin.Finance.Methods.as_view(), name='director/finance/methods'),
    path('director/finance/methods/<uuid:id>', views.Admin.Finance.Methods.Method.as_view(),
         name='director/finance/method/method'),
    path('director/finance/methods/<uuid:id>/delete', views.Admin.Finance.Methods.Method.Delete.as_view(),
         name='director/finance/methods/method/delete'),
    path('director/units', RedirectView.as_view(url="director/units/overview"), name='director/units'),
    path('director/units/overview', views.Admin.Units.as_view(), name='director/units'),
    path('director/menu', RedirectView.as_view(url="director/menu/products"), name='director/menu'),
    path('director/menu/products', views.Admin.Menu.Products.as_view(), name='director/menu/products'),
    path('director/menu/products/<uuid:id>', views.Admin.Menu.Products.Product.as_view(),
         name='director/menu/products/product'),
    path('director/menu/products/<uuid:id>/delete', views.Admin.Menu.Products.Product.Delete.as_view(),
         name='director/menu/products/product/delete'),
    path('director/menu/items', views.Admin.Menu.Items.as_view(), name='director/menu/items'),
    path('director/menu/items/<uuid:id>', views.Admin.Menu.Items.Item.as_view(),
         name='director/menu/items/item'),
    path('director/menu/items/<uuid:id>/delete', views.Admin.Menu.Items.Item.Delete.as_view(),
         name='director/menu/items/item/delete'),
]
