# Generated by Django 3.0.2 on 2020-01-14 21:29

from django.db import migrations

currencies = [
    {
        "pk": 784,
        "name": "UAE Dirham",
        "code": "AED",
        "symbol": "د.إ",
        "countries": [
            "AE"
        ],
        "subunit": "fils"
    },
    {
        "pk": 971,
        "name": "Afghani",
        "code": "AFN",
        "symbol": "؋",
        "countries": [
            "AF"
        ],
        "subunit": "pul"
    },
    {
        "pk": 8,
        "name": "Lek",
        "code": "ALL",
        "symbol": "L",
        "countries": [
            "AL"
        ],
        "subunit": "qindarkë"
    },
    {
        "pk": 51,
        "name": "Armenian Dram",
        "code": "AMD",
        "symbol": "դր.",
        "countries": [
            "AM"
        ],
        "subunit": "luma"
    },
    {
        "pk": 532,
        "name": "Netherlands Antillean Guilder",
        "code": "ANG",
        "symbol": "ƒ",
        "countries": [
            "CW",
            "SX"
        ],
        "subunit": "cent"
    },
    {
        "pk": 973,
        "name": "Kwanza",
        "code": "AOA",
        "symbol": "Kz",
        "countries": [
            "AO"
        ],
        "subunit": "cêntimo"
    },
    {
        "pk": 32,
        "name": "Argentine Peso",
        "code": "ARS",
        "symbol": "$",
        "countries": [
            "AR"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 36,
        "name": "Australian Dollar",
        "code": "AUD",
        "symbol": "$",
        "countries": [
            "AU",
            "CX",
            "CC",
            "HM",
            "KI",
            "NR",
            "NF",
            "TV"
        ],
        "subunit": "cent"
    },
    {
        "pk": 533,
        "name": "Aruban Florin",
        "code": "AWG",
        "symbol": "ƒ",
        "countries": [
            "AW"
        ],
        "subunit": "cent"
    },
    {
        "pk": 944,
        "name": "Azerbaijanian Manat",
        "code": "AZN",
        "symbol": "m",
        "countries": [
            "AZ"
        ],
        "subunit": "qəpik"
    },
    {
        "pk": 977,
        "name": "Convertible Mark",
        "code": "BAM",
        "symbol": "КМ",
        "countries": [
            "BA"
        ],
        "subunit": "fening"
    },
    {
        "pk": 52,
        "name": "Barbados Dollar",
        "code": "BBD",
        "symbol": "$",
        "countries": [
            "BB"
        ],
        "subunit": "cent"
    },
    {
        "pk": 50,
        "name": "Taka",
        "code": "BDT",
        "symbol": "৳",
        "countries": [
            "BD"
        ],
        "subunit": "paisa"
    },
    {
        "pk": 975,
        "name": "Bulgarian Lev",
        "code": "BGN",
        "symbol": "лв",
        "countries": [
            "BG"
        ],
        "subunit": "stotinka"
    },
    {
        "pk": 48,
        "name": "Bahraini Dinar",
        "code": "BHD",
        "symbol": ".د.ب",
        "countries": [
            "BH"
        ],
        "subunit": "fils"
    },
    {
        "pk": 108,
        "name": "Burundi Franc",
        "code": "BIF",
        "symbol": "Fr",
        "countries": [
            "BI"
        ],
        "subunit": "centime"
    },
    {
        "pk": 60,
        "name": "Bermudian Dollar",
        "code": "BMD",
        "symbol": "$",
        "countries": [
            "BM"
        ],
        "subunit": "cent"
    },
    {
        "pk": 96,
        "name": "Brunei Dollar",
        "code": "BND",
        "symbol": "$",
        "countries": [
            "BN"
        ],
        "subunit": "sen"
    },
    {
        "pk": 68,
        "name": "Boliviano",
        "code": "BOB",
        "symbol": "Bs.",
        "countries": [
            "BO"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 986,
        "name": "Brazilian Real",
        "code": "BRL",
        "symbol": "R$",
        "countries": [
            "BR"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 44,
        "name": "Bahamian Dollar",
        "code": "BSD",
        "symbol": "$",
        "countries": [
            "BS"
        ],
        "subunit": "cent"
    },
    {
        "pk": 64,
        "name": "Ngultrum",
        "code": "BTN",
        "symbol": "Nu.",
        "countries": [
            "BT"
        ],
        "subunit": "chetrum"
    },
    {
        "pk": 72,
        "name": "Pula",
        "code": "BWP",
        "symbol": "P",
        "countries": [
            "BW"
        ],
        "subunit": "thebe"
    },
    {
        "pk": 974,
        "name": "Belarussian Ruble",
        "code": "BYR",
        "symbol": "Br",
        "countries": [
            "BY"
        ],
        "subunit": "kapyeyka"
    },
    {
        "pk": 84,
        "name": "Belize Dollar",
        "code": "BZD",
        "symbol": "$",
        "countries": [
            "BZ"
        ],
        "subunit": "cent"
    },
    {
        "pk": 124,
        "name": "Canadian Dollar",
        "code": "CAD",
        "symbol": "$",
        "countries": [
            "CA"
        ],
        "subunit": "cent"
    },
    {
        "pk": 976,
        "name": "Congolese Franc",
        "code": "CDF",
        "symbol": "Fr",
        "countries": [
            "CD"
        ],
        "subunit": "centime"
    },
    {
        "pk": 756,
        "name": "Swiss Franc",
        "code": "CHF",
        "symbol": "Fr",
        "countries": [
            "LI",
            "CH"
        ],
        "subunit": "rappen"
    },
    {
        "pk": 152,
        "name": "Chilean Peso",
        "code": "CLP",
        "symbol": "$",
        "countries": [
            "CL"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 156,
        "name": "Yuan Renminbi",
        "code": "CNY",
        "symbol": "¥",
        "countries": [
            "CN"
        ],
        "subunit": "fen"
    },
    {
        "pk": 170,
        "name": "Colombian Peso",
        "code": "COP",
        "symbol": "$",
        "countries": [
            "CO"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 188,
        "name": "Costa Rican Colon",
        "code": "CRC",
        "symbol": "₡",
        "countries": [
            "CR"
        ],
        "subunit": "cêntimo"
    },
    {
        "pk": 931,
        "name": "Peso Convertible",
        "code": "CUC",
        "symbol": "$",
        "countries": [
            "CU"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 192,
        "name": "Cuban Peso",
        "code": "CUP",
        "symbol": "$",
        "countries": [
            "CU"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 132,
        "name": "Cape Verde Escudo",
        "code": "CVE",
        "symbol": "Esc or $",
        "countries": [
            "CV"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 203,
        "name": "Czech Koruna",
        "code": "CZK",
        "symbol": "Kč",
        "countries": [
            "CZ"
        ],
        "subunit": "haléř"
    },
    {
        "pk": 262,
        "name": "Djibouti Franc",
        "code": "DJF",
        "symbol": "Fr",
        "countries": [
            "DJ"
        ],
        "subunit": "centime"
    },
    {
        "pk": 208,
        "name": "Danish Krone",
        "code": "DKK",
        "symbol": "kr",
        "countries": [
            "DK",
            "FO",
            "GL"
        ],
        "subunit": "øre"
    },
    {
        "pk": 214,
        "name": "Dominican Peso",
        "code": "DOP",
        "symbol": "$",
        "countries": [
            "DO"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 12,
        "name": "Algerian Dinar",
        "code": "DZD",
        "symbol": "د.ج",
        "countries": [
            "DZ"
        ],
        "subunit": "Santeem"
    },
    {
        "pk": 818,
        "name": "Egyptian Pound",
        "code": "EGP",
        "symbol": "ج.م",
        "countries": [
            "EG"
        ],
        "subunit": "piaster"
    },
    {
        "pk": 232,
        "name": "Nakfa",
        "code": "ERN",
        "symbol": "Nfk",
        "countries": [
            "ER"
        ],
        "subunit": "cent"
    },
    {
        "pk": 230,
        "name": "Ethiopian Birr",
        "code": "ETB",
        "symbol": "Br",
        "countries": [
            "ET"
        ],
        "subunit": "santim"
    },
    {
        "pk": 978,
        "name": "Euro",
        "code": "EUR",
        "symbol": "€",
        "countries": [
            "AX",
            "AD",
            "AT",
            "BE",
            "CY",
            "EE",
            "FI",
            "FR",
            "GF",
            "TF",
            "DE",
            "GR",
            "GP",
            "IE",
            "IT",
            "LU",
            "MT",
            "MQ",
            "YT",
            "MC",
            "ME",
            "NL",
            "PT",
            "RE",
            "BL",
            "MF",
            "PM",
            "SM",
            "SK",
            "SI",
            "ES",
            "VA"
        ],
        "subunit": "cent"
    },
    {
        "pk": 242,
        "name": "Fiji Dollar",
        "code": "FJD",
        "symbol": "$",
        "countries": [
            "FJ"
        ],
        "subunit": "cent"
    },
    {
        "pk": 238,
        "name": "Falkland Islands Pound",
        "code": "FKP",
        "symbol": "£",
        "countries": [
            "FK"
        ],
        "subunit": "penny"
    },
    {
        "pk": 826,
        "name": "Pound Sterling",
        "code": "GBP",
        "symbol": "£",
        "countries": [
            "GG",
            "IM",
            "JE",
            "GB"
        ],
        "subunit": "penny"
    },
    {
        "pk": 981,
        "name": "Lari",
        "code": "GEL",
        "symbol": "ლ",
        "countries": [
            "GE"
        ],
        "subunit": "tetri"
    },
    {
        "pk": 936,
        "name": "Ghana Cedi",
        "code": "GHS",
        "symbol": "₵",
        "countries": [
            "GH"
        ],
        "subunit": "pesewa"
    },
    {
        "pk": 292,
        "name": "Gibraltar Pound",
        "code": "GIP",
        "symbol": "£",
        "countries": [
            "GI"
        ],
        "subunit": "penny"
    },
    {
        "pk": 270,
        "name": "Dalasi",
        "code": "GMD",
        "symbol": "D",
        "countries": [
            "GM"
        ],
        "subunit": "butut"
    },
    {
        "pk": 324,
        "name": "Guinea Franc",
        "code": "GNF",
        "symbol": "Fr",
        "countries": [
            "GN"
        ],
        "subunit": "centime"
    },
    {
        "pk": 320,
        "name": "Quetzal",
        "code": "GTQ",
        "symbol": "Q",
        "countries": [
            "GT"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 328,
        "name": "Guyana Dollar",
        "code": "GYD",
        "symbol": "$",
        "countries": [
            "GY"
        ],
        "subunit": "cent"
    },
    {
        "pk": 344,
        "name": "Hong Kong Dollar",
        "code": "HKD",
        "symbol": "$",
        "countries": [
            "HK"
        ],
        "subunit": "cent"
    },
    {
        "pk": 340,
        "name": "Lempira",
        "code": "HNL",
        "symbol": "L",
        "countries": [
            "HN"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 191,
        "name": "Croatian Kuna",
        "code": "HRK",
        "symbol": "kn",
        "countries": [
            "HR"
        ],
        "subunit": "lipa"
    },
    {
        "pk": 332,
        "name": "Gourde",
        "code": "HTG",
        "symbol": "G",
        "countries": [
            "HT"
        ],
        "subunit": "centime"
    },
    {
        "pk": 348,
        "name": "Forint",
        "code": "HUF",
        "symbol": "Ft",
        "countries": [
            "HU"
        ],
        "subunit": "fillér"
    },
    {
        "pk": 360,
        "name": "Rupiah",
        "code": "IDR",
        "symbol": "Rp",
        "countries": [
            "ID"
        ],
        "subunit": "sen"
    },
    {
        "pk": 376,
        "name": "New Israeli Sheqel",
        "code": "ILS",
        "symbol": "₪",
        "countries": [
            "IL"
        ],
        "subunit": "agora"
    },
    {
        "pk": 356,
        "name": "Indian Rupee",
        "code": "INR",
        "symbol": "₹",
        "countries": [
            "BT",
            "IN"
        ],
        "subunit": "paisa"
    },
    {
        "pk": 368,
        "name": "Iraqi Dinar",
        "code": "IQD",
        "symbol": "ع.د",
        "countries": [
            "IQ"
        ],
        "subunit": "fils"
    },
    {
        "pk": 364,
        "name": "Iranian Rial",
        "code": "IRR",
        "symbol": "﷼",
        "countries": [
            "IR"
        ],
        "subunit": "NULL"
    },
    {
        "pk": 352,
        "name": "Iceland Krona",
        "code": "ISK",
        "symbol": "kr",
        "countries": [
            "IS"
        ],
        "subunit": "eyrir"
    },
    {
        "pk": 388,
        "name": "Jamaican Dollar",
        "code": "JMD",
        "symbol": "$",
        "countries": [
            "JM"
        ],
        "subunit": "cent"
    },
    {
        "pk": 400,
        "name": "Jordanian Dinar",
        "code": "JOD",
        "symbol": "د.ا",
        "countries": [
            "JO"
        ],
        "subunit": "piastre"
    },
    {
        "pk": 392,
        "name": "Yen",
        "code": "JPY",
        "symbol": "¥",
        "countries": [
            "JP"
        ],
        "subunit": "sen"
    },
    {
        "pk": 404,
        "name": "Kenyan Shilling",
        "code": "KES",
        "symbol": "Sh",
        "countries": [
            "KE"
        ],
        "subunit": "cent"
    },
    {
        "pk": 417,
        "name": "Som",
        "code": "KGS",
        "symbol": "лв",
        "countries": [
            "KG"
        ],
        "subunit": "tyiyn"
    },
    {
        "pk": 116,
        "name": "Riel",
        "code": "KHR",
        "symbol": "៛",
        "countries": [
            "KH"
        ],
        "subunit": "sen"
    },
    {
        "pk": 174,
        "name": "Comoro Franc",
        "code": "KMF",
        "symbol": "Fr",
        "countries": [
            "KM"
        ],
        "subunit": "centime"
    },
    {
        "pk": 408,
        "name": "North Korean Won",
        "code": "KPW",
        "symbol": "₩",
        "countries": [
            "KP"
        ],
        "subunit": "chon"
    },
    {
        "pk": 410,
        "name": "Won",
        "code": "KRW",
        "symbol": "₩",
        "countries": [
            "KR"
        ],
        "subunit": "jeon"
    },
    {
        "pk": 414,
        "name": "Kuwaiti Dinar",
        "code": "KWD",
        "symbol": "د.ك",
        "countries": [
            "KW"
        ],
        "subunit": "fils"
    },
    {
        "pk": 136,
        "name": "Cayman Islands Dollar",
        "code": "KYD",
        "symbol": "$",
        "countries": [
            "KY"
        ],
        "subunit": "cent"
    },
    {
        "pk": 398,
        "name": "Tenge",
        "code": "KZT",
        "symbol": "₸",
        "countries": [
            "KZ"
        ],
        "subunit": "tïın"
    },
    {
        "pk": 418,
        "name": "Kip",
        "code": "LAK",
        "symbol": "₭",
        "countries": [
            "LA"
        ],
        "subunit": "att"
    },
    {
        "pk": 422,
        "name": "Lebanese Pound",
        "code": "LBP",
        "symbol": "ل.ل",
        "countries": [
            "LB"
        ],
        "subunit": "piastre"
    },
    {
        "pk": 144,
        "name": "Sri Lanka Rupee",
        "code": "LKR",
        "symbol": "Rs",
        "countries": [
            "LK"
        ],
        "subunit": "cent"
    },
    {
        "pk": 430,
        "name": "Liberian Dollar",
        "code": "LRD",
        "symbol": "$",
        "countries": [
            "LR"
        ],
        "subunit": "cent"
    },
    {
        "pk": 426,
        "name": "Loti",
        "code": "LSL",
        "symbol": "L",
        "countries": [
            "LS"
        ],
        "subunit": "sente"
    },
    {
        "pk": 440,
        "name": "Lithuanian Litas",
        "code": "LTL",
        "symbol": "Lt",
        "countries": [
            "LT"
        ],
        "subunit": "centas"
    },
    {
        "pk": 1,
        "name": "Latvian Lats",
        "code": "LVL",
        "symbol": "NULL",
        "countries": [
            "LV"
        ],
        "subunit": "NULL"
    },
    {
        "pk": 434,
        "name": "Libyan Dinar",
        "code": "LYD",
        "symbol": "ل.د",
        "countries": [
            "LY"
        ],
        "subunit": "dirham"
    },
    {
        "pk": 504,
        "name": "Moroccan Dirham",
        "code": "MAD",
        "symbol": "د.م.",
        "countries": [
            "MA",
            "EH"
        ],
        "subunit": "centime"
    },
    {
        "pk": 498,
        "name": "Moldovan Leu",
        "code": "MDL",
        "symbol": "L",
        "countries": [
            "MD"
        ],
        "subunit": "ban"
    },
    {
        "pk": 969,
        "name": "Malagasy Ariary",
        "code": "MGA",
        "symbol": "Ar",
        "countries": [
            "MG"
        ],
        "subunit": "iraimbilanja"
    },
    {
        "pk": 807,
        "name": "Denar",
        "code": "MKD",
        "symbol": "ден",
        "countries": [
            "MK"
        ],
        "subunit": "deni"
    },
    {
        "pk": 104,
        "name": "Kyat",
        "code": "MMK",
        "symbol": "Ks",
        "countries": [
            "MM"
        ],
        "subunit": "pya"
    },
    {
        "pk": 496,
        "name": "Tugrik",
        "code": "MNT",
        "symbol": "₮",
        "countries": [
            "MN"
        ],
        "subunit": "möngö"
    },
    {
        "pk": 446,
        "name": "Pataca",
        "code": "MOP",
        "symbol": "P",
        "countries": [
            "MO"
        ],
        "subunit": "avo"
    },
    {
        "pk": 478,
        "name": "Ouguiya",
        "code": "MRO",
        "symbol": "UM",
        "countries": [
            "MR"
        ],
        "subunit": "khoums"
    },
    {
        "pk": 480,
        "name": "Mauritius Rupee",
        "code": "MUR",
        "symbol": "₨",
        "countries": [
            "MU"
        ],
        "subunit": "cent"
    },
    {
        "pk": 462,
        "name": "Rufiyaa",
        "code": "MVR",
        "symbol": ".ރ",
        "countries": [
            "MV"
        ],
        "subunit": "laari"
    },
    {
        "pk": 454,
        "name": "Kwacha",
        "code": "MWK",
        "symbol": "MK",
        "countries": [
            "MW"
        ],
        "subunit": "tambala"
    },
    {
        "pk": 484,
        "name": "Mexican Peso",
        "code": "MXN",
        "symbol": "$",
        "countries": [
            "MX"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 458,
        "name": "Malaysian Ringgit",
        "code": "MYR",
        "symbol": "RM",
        "countries": [
            "MY"
        ],
        "subunit": "sen"
    },
    {
        "pk": 943,
        "name": "Mozambique Metical",
        "code": "MZN",
        "symbol": "MT",
        "countries": [
            "MZ"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 516,
        "name": "Namibia Dollar",
        "code": "NAD",
        "symbol": "$",
        "countries": [
            "NA"
        ],
        "subunit": "cent"
    },
    {
        "pk": 566,
        "name": "Naira",
        "code": "NGN",
        "symbol": "₦",
        "countries": [
            "NG"
        ],
        "subunit": "kobo"
    },
    {
        "pk": 558,
        "name": "Cordoba Oro",
        "code": "NIO",
        "symbol": "C$",
        "countries": [
            "NI"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 578,
        "name": "Norwegian Krone",
        "code": "NOK",
        "symbol": "kr",
        "countries": [
            "BV",
            "NO",
            "SJ"
        ],
        "subunit": "øre"
    },
    {
        "pk": 524,
        "name": "Nepalese Rupee",
        "code": "NPR",
        "symbol": "₨",
        "countries": [
            "NP"
        ],
        "subunit": "paisa"
    },
    {
        "pk": 554,
        "name": "New Zealand Dollar",
        "code": "NZD",
        "symbol": "$",
        "countries": [
            "CK",
            "NZ",
            "NU",
            "PN",
            "TK"
        ],
        "subunit": "cent"
    },
    {
        "pk": 512,
        "name": "Rial Omani",
        "code": "OMR",
        "symbol": "ر.ع.",
        "countries": [
            "OM"
        ],
        "subunit": "Baisa"
    },
    {
        "pk": 590,
        "name": "Balboa",
        "code": "PAB",
        "symbol": "B/.",
        "countries": [
            "PA"
        ],
        "subunit": "centésimo"
    },
    {
        "pk": 604,
        "name": "Nuevo Sol",
        "code": "PEN",
        "symbol": "S/.",
        "countries": [
            "PE"
        ],
        "subunit": "cêntimo"
    },
    {
        "pk": 598,
        "name": "Kina",
        "code": "PGK",
        "symbol": "K",
        "countries": [
            "PG"
        ],
        "subunit": "toea"
    },
    {
        "pk": 608,
        "name": "Philippine Peso",
        "code": "PHP",
        "symbol": "₱",
        "countries": [
            "PH"
        ],
        "subunit": "centavo"
    },
    {
        "pk": 586,
        "name": "Pakistan Rupee",
        "code": "PKR",
        "symbol": "₨",
        "countries": [
            "PK"
        ],
        "subunit": "paisa"
    },
    {
        "pk": 985,
        "name": "Zloty",
        "code": "PLN",
        "symbol": "zł",
        "countries": [
            "PL"
        ],
        "subunit": "grosz"
    },
    {
        "pk": 600,
        "name": "Guarani",
        "code": "PYG",
        "symbol": "₲",
        "countries": [
            "PY"
        ],
        "subunit": "cêntimo"
    },
    {
        "pk": 634,
        "name": "Qatari Rial",
        "code": "QAR",
        "symbol": "ر.ق",
        "countries": [
            "QA"
        ],
        "subunit": "dirham"
    },
    {
        "pk": 946,
        "name": "New Romanian Leu",
        "code": "RON",
        "symbol": "L",
        "countries": [
            "RO"
        ],
        "subunit": "ban"
    },
    {
        "pk": 941,
        "name": "Serbian Dinar",
        "code": "RSD",
        "symbol": "дин.",
        "countries": [
            "RS"
        ],
        "subunit": "para"
    },
    {
        "pk": 643,
        "name": "Russian Ruble",
        "code": "RUB",
        "symbol": "руб.",
        "countries": [
            "RU"
        ],
        "subunit": "kopek"
    },
    {
        "pk": 646,
        "name": "Rwanda Franc",
        "code": "RWF",
        "symbol": "Fr",
        "countries": [
            "RW"
        ],
        "subunit": "centime"
    },
    {
        "pk": 682,
        "name": "Saudi Riyal",
        "code": "SAR",
        "symbol": "ر.س",
        "countries": [
            "SA"
        ],
        "subunit": "halala"
    },
    {
        "pk": 90,
        "name": "Solomon Islands Dollar",
        "code": "SBD",
        "symbol": "$",
        "countries": [
            "SB"
        ],
        "subunit": "cent"
    },
    {
        "pk": 690,
        "name": "Seychelles Rupee",
        "code": "SCR",
        "symbol": "₨",
        "countries": [
            "SC"
        ],
        "subunit": "cent"
    },
    {
        "pk": 938,
        "name": "Sudanese Pound",
        "code": "SDG",
        "symbol": "£",
        "countries": [
            "SD"
        ],
        "subunit": "piastre"
    },
    {
        "pk": 752,
        "name": "Swedish Krona",
        "code": "SEK",
        "symbol": "kr",
        "countries": [
            "SE"
        ],
        "subunit": "öre"
    },
    {
        "pk": 702,
        "name": "Singapore Dollar",
        "code": "SGD",
        "symbol": "$",
        "countries": [
            "SG"
        ],
        "subunit": "cent"
    },
    {
        "pk": 654,
        "name": "Saint Helena Pound",
        "code": "SHP",
        "symbol": "£",
        "countries": [
            "SH"
        ],
        "subunit": "penny"
    },
    {
        "pk": 694,
        "name": "Leone",
        "code": "SLL",
        "symbol": "Le",
        "countries": [
            "SL"
        ],
        "subunit": "cent"
    },
    {
        "pk": 706,
        "name": "Somali Shilling",
        "code": "SOS",
        "symbol": "Sh",
        "countries": [
            "SO"
        ],
        "subunit": "cent"
    },
    {
        "pk": 968,
        "name": "Surinam Dollar",
        "code": "SRD",
        "symbol": "$",
        "countries": [
            "SR"
        ],
        "subunit": "cent"
    },
    {
        "pk": 728,
        "name": "South Sudanese Pound",
        "code": "SSP",
        "symbol": "£",
        "countries": [
            "SS"
        ],
        "subunit": "piastre"
    },
    {
        "pk": 678,
        "name": "Dobra",
        "code": "STD",
        "symbol": "Db",
        "countries": [
            "ST"
        ],
        "subunit": "cêntimo"
    },
    {
        "pk": 2,
        "name": "El Salvador Colon",
        "code": "SVC",
        "symbol": "NULL",
        "countries": [
            "SV"
        ],
        "subunit": "NULL"
    },
    {
        "pk": 760,
        "name": "Syrian Pound",
        "code": "SYP",
        "symbol": "ل.س",
        "countries": [
            "SY"
        ],
        "subunit": "piastre"
    },
    {
        "pk": 748,
        "name": "Lilangeni",
        "code": "SZL",
        "symbol": "L",
        "countries": [
            "SZ"
        ],
        "subunit": "cent"
    },
    {
        "pk": 764,
        "name": "Baht",
        "code": "THB",
        "symbol": "฿",
        "countries": [
            "TH"
        ],
        "subunit": "satang"
    },
    {
        "pk": 972,
        "name": "Somoni",
        "code": "TJS",
        "symbol": "ЅМ",
        "countries": [
            "TJ"
        ],
        "subunit": "diram"
    },
    {
        "pk": 934,
        "name": "Turkmenistan New Manat",
        "code": "TMT",
        "symbol": "m",
        "countries": [
            "TM"
        ],
        "subunit": "tennesi"
    },
    {
        "pk": 788,
        "name": "Tunisian Dinar",
        "code": "TND",
        "symbol": "د.ت",
        "countries": [
            "TN"
        ],
        "subunit": "millime"
    },
    {
        "pk": 776,
        "name": "Pa'anga",
        "code": "TOP",
        "symbol": "T$",
        "countries": [
            "TO"
        ],
        "subunit": "seniti"
    },
    {
        "pk": 949,
        "name": "Turkish Lira",
        "code": "TRY",
        "symbol": "NULL",
        "countries": [
            "TR"
        ],
        "subunit": "kuruş"
    },
    {
        "pk": 780,
        "name": "Trinidad and Tobago Dollar",
        "code": "TTD",
        "symbol": "$",
        "countries": [
            "TT"
        ],
        "subunit": "cent"
    },
    {
        "pk": 901,
        "name": "New Taiwan Dollar",
        "code": "TWD",
        "symbol": "$",
        "countries": [
            "TW"
        ],
        "subunit": "cent"
    },
    {
        "pk": 834,
        "name": "Tanzanian Shilling",
        "code": "TZS",
        "symbol": "Sh",
        "countries": [
            "TZ"
        ],
        "subunit": "cent"
    },
    {
        "pk": 980,
        "name": "Hryvnia",
        "code": "UAH",
        "symbol": "₴",
        "countries": [
            "UA"
        ],
        "subunit": "kopiyka"
    },
    {
        "pk": 800,
        "name": "Uganda Shilling",
        "code": "UGX",
        "symbol": "Sh",
        "countries": [
            "UG"
        ],
        "subunit": "cent"
    },
    {
        "pk": 840,
        "name": "US Dollar",
        "code": "USD",
        "symbol": "$",
        "countries": [
            "AS",
            "BQ",
            "IO",
            "EC",
            "SV",
            "GU",
            "HT",
            "MH",
            "FM",
            "MP",
            "PW",
            "PA",
            "PR",
            "TL",
            "TC",
            "US",
            "UM",
            "VG",
            "VI"
        ],
        "subunit": "cent"
    },
    {
        "pk": 858,
        "name": "Peso Uruguayo",
        "code": "UYU",
        "symbol": "$",
        "countries": [
            "UY"
        ],
        "subunit": "centésimo"
    },
    {
        "pk": 860,
        "name": "Uzbekistan Sum",
        "code": "UZS",
        "symbol": "лв",
        "countries": [
            "UZ"
        ],
        "subunit": "tiyin"
    },
    {
        "pk": 937,
        "name": "Bolivar",
        "code": "VEF",
        "symbol": "Bs F",
        "countries": [
            "VE"
        ],
        "subunit": "cêntimo"
    },
    {
        "pk": 704,
        "name": "Dong",
        "code": "VND",
        "symbol": "₫",
        "countries": [
            "VN"
        ],
        "subunit": "hào"
    },
    {
        "pk": 548,
        "name": "Vatu",
        "code": "VUV",
        "symbol": "Vt",
        "countries": [
            "VU"
        ],
        "subunit": "NULL"
    },
    {
        "pk": 882,
        "name": "Tala",
        "code": "WST",
        "symbol": "T",
        "countries": [
            "WS"
        ],
        "subunit": "sene"
    },
    {
        "pk": 950,
        "name": "CFA Franc BEAC",
        "code": "XAF",
        "symbol": "Fr",
        "countries": [
            "CM",
            "CF",
            "TD",
            "CG",
            "GQ",
            "GA"
        ],
        "subunit": "centime"
    },
    {
        "pk": 951,
        "name": "East Caribbean Dollar",
        "code": "XCD",
        "symbol": "$",
        "countries": [
            "AI",
            "AG",
            "DM",
            "GD",
            "MS",
            "KN",
            "LC",
            "VC"
        ],
        "subunit": "cent"
    },
    {
        "pk": 952,
        "name": "CFA Franc BCEAO",
        "code": "XOF",
        "symbol": "Fr",
        "countries": [
            "BJ",
            "BF",
            "CI",
            "GW",
            "ML",
            "NE",
            "SN",
            "TG"
        ],
        "subunit": "centime"
    },
    {
        "pk": 953,
        "name": "CFP Franc",
        "code": "XPF",
        "symbol": "Fr",
        "countries": [
            "PF",
            "NC",
            "WF"
        ],
        "subunit": "centime"
    },
    {
        "pk": 886,
        "name": "Yemeni Rial",
        "code": "YER",
        "symbol": "﷼",
        "countries": [
            "YE"
        ],
        "subunit": "fils"
    },
    {
        "pk": 710,
        "name": "Rand",
        "code": "ZAR",
        "symbol": "R",
        "countries": [
            "LS",
            "NA",
            "ZA"
        ],
        "subunit": "cent"
    },
    {
        "pk": 967,
        "name": "Zambian Kwacha",
        "code": "ZMW",
        "symbol": "ZK",
        "countries": [
            "ZM"
        ],
        "subunit": "ngwee"
    },
    {
        "pk": 3,
        "name": "Zimbabwe Dollar",
        "code": "ZWL",
        "symbol": "NULL",
        "countries": [
            "ZW"
        ],
        "subunit": "NULL"
    }
]


def add_countries(apps, schema_editor):
    Currency = apps.get_model('posapp', 'Currency')
    for item in currencies:
        currency = Currency()
        currency.pk = item["pk"]
        currency.code = item["code"]
        currency.name = item["name"]
        currency.symbol = item["symbol"]
        currency.subunit = item["subunit"]
        currency.ratio = 1
        countries = ""
        for country in item["countries"]:
            countries += f",{country}" if countries else country
        currency.countries = countries
        currency.save()


class Migration(migrations.Migration):
    dependencies = [
        ('posapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_countries),
    ]
