# Generated by Django 3.0.2 on 2020-01-14 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_auto_20200114_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminproduct',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminproduct',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='posapp.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iteminproduct',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posapp.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='ratio',
            field=models.FloatField(default=0),
        ),
    ]
