# Generated by Django 3.0.2 on 2020-01-14 21:29

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=3, null=True)),
                ('symbol', models.CharField(max_length=8, null=True)),
                ('countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('subunit', models.CharField(max_length=1024)),
                ('ratio', models.FloatField()),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('C', 'Created'), ('P', 'Paid')], default='C', max_length=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('O', 'Ordered'), ('P', 'Being prepared'), ('T', 'To be served'), ('S', 'Served')], default='O', max_length=1)),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('orderedAt', models.DateTimeField(auto_now_add=True)),
                ('preparingAt', models.DateTimeField(blank=True, null=True)),
                ('preparedAt', models.DateTimeField(blank=True, null=True)),
                ('servedAt', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('symbol', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('symbol', models.CharField(max_length=16)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posapp.UnitGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('O', 'Open'), ('P', 'Paid')], default='O', max_length=1)),
                ('openedAt', models.DateTimeField(auto_now_add=True)),
                ('closedAt', models.DateTimeField(blank=True, null=True)),
                ('products', models.ManyToManyField(through='posapp.ProductInTicket', to='posapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='productinticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.Ticket'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('currency', models.ForeignKey(limit_choices_to={'enabled': True}, on_delete=django.db.models.deletion.PROTECT, to='posapp.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posapp.PaymentMethod')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posapp.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payments',
            field=models.ManyToManyField(through='posapp.PaymentInOrder', to='posapp.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='posapp.Ticket'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('unitGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posapp.UnitGroup')),
            ],
        ),
    ]
