# Generated by Django 3.0.2 on 2020-01-17 15:48

from django.db import migrations
from django.db.migrations import RenameModel, RenameField


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0004_auto_20200117_1538'),
    ]

    operations = [
        RenameModel("Ticket", "Tab"),
        RenameModel("ProductInTicket", "ProductInTab"),
        RenameField("Order", "ticket", "tab"),
        RenameField("ProductInTab", "ticket", "tab"),
    ]
