# Generated by Django 3.0.2 on 2020-01-22 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posapp', '0005_auto_20200117_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='iteminproduct',
            options={'verbose_name_plural': 'Items in products'},
        ),
        migrations.AlterModelOptions(
            name='paymentinorder',
            options={'verbose_name_plural': 'Payments in orders'},
        ),
        migrations.AlterModelOptions(
            name='productintab',
            options={'verbose_name_plural': 'Products in tabs'},
        ),
        migrations.AlterModelOptions(
            name='tab',
            options={'permissions': [('order_product', 'Can order a product')]},
        ),
        migrations.AddField(
            model_name='product',
            name='items',
            field=models.ManyToManyField(through='posapp.ItemInProduct', to='posapp.Item'),
        ),
        migrations.AlterField(
            model_name='productintab',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Till',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('openedAt', models.DateTimeField(auto_now_add=True)),
                ('countedAt', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('O', 'Open'), ('C', 'Counted')], default='O', max_length=1)),
                ('cashiers', models.ManyToManyField(related_name='tills_owned', to=settings.AUTH_USER_MODEL)),
                ('changePaymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tillsAsChange', to='posapp.PaymentMethod')),
                ('countedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tills_counted', to=settings.AUTH_USER_MODEL)),
                ('paymentMethods', models.ManyToManyField(to='posapp.PaymentMethod')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='till',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='posapp.Till'),
            preserve_default=False,
        ),
    ]
