# Generated by Django 3.0.2 on 2020-01-22 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0006_auto_20200122_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_temp_tab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posapp.Tab'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_till',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posapp.Till'),
        ),
        migrations.AlterField(
            model_name='till',
            name='cashiers',
            field=models.ManyToManyField(limit_choices_to={'pudaUser.is_cashier': True}, related_name='tills_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='till',
            name='countedBy',
            field=models.ForeignKey(limit_choices_to={'pudaUser.is_manager': True}, on_delete=django.db.models.deletion.PROTECT, related_name='tills_counted', to=settings.AUTH_USER_MODEL),
        ),
    ]
