# Generated by Django 3.0.2 on 2020-01-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0007_auto_20200122_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
