# Generated by Django 3.0.2 on 2020-01-24 10:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0009_user_mobile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='till',
            name='state',
            field=models.CharField(choices=[('O', 'Open'), ('S', 'Stopped'), ('C', 'Counted')], default='O', max_length=1),
        ),
        migrations.CreateModel(
            name='DepositValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.Deposit')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posapp.PaymentMethod')),
            ],
            options={
                'verbose_name_plural': 'Deposit values',
            },
        ),
        migrations.AddField(
            model_name='deposit',
            name='values',
            field=models.ManyToManyField(through='posapp.DepositValue', to='posapp.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='till',
            name='deposit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='posapp.Deposit'),
            preserve_default=False,
        ),
    ]
