# Generated by Django 3.0.2 on 2020-02-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0010_auto_20200124_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='till',
            name='stoppedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
