# Generated by Django 3.0.2 on 2020-02-20 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0011_till_stoppedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TillMoneyCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='TillPaymentOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('depositAmount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Till payment options',
            },
        ),
        migrations.RemoveField(
            model_name='depositvalue',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='depositvalue',
            name='method',
        ),
        migrations.RenameField(
            model_name='till',
            old_name='changePaymentMethod',
            new_name='changeMethod',
        ),
        migrations.RemoveField(
            model_name='till',
            name='deposit',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='changeAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='till',
            name='depositAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='till',
            name='cashiers',
            field=models.ManyToManyField(limit_choices_to={'is_waiter': True}, related_name='tills_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='till',
            name='countedBy',
            field=models.ForeignKey(limit_choices_to={'is_manager': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tills_counted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='DepositValue',
        ),
        migrations.AddField(
            model_name='tillpaymentoptions',
            name='changeMethod',
            field=models.ForeignKey(limit_choices_to={'changeAllowed': True, 'currency__enabled': True}, on_delete=django.db.models.deletion.PROTECT, related_name='optionsAsChange', to='posapp.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='tillpaymentoptions',
            name='methods',
            field=models.ManyToManyField(related_name='paymentOptions', to='posapp.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='tillmoneycount',
            name='paymentMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posapp.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='tillmoneycount',
            name='till',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.Till'),
        ),
        migrations.RemoveField(
            model_name='till',
            name='paymentMethods',
        ),
        migrations.AddField(
            model_name='till',
            name='paymentMethods',
            field=models.ManyToManyField(related_name='tillsEnabled', through='posapp.TillMoneyCount', to='posapp.PaymentMethod'),
        ),
    ]
