# Generated by Django 3.0.2 on 2020-02-24 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0013_tilledit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInTab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posapp.TillMoneyCount')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='posapp.Tab')),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentinorder',
            name='method',
        ),
        migrations.RemoveField(
            model_name='paymentinorder',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PaymentInOrder',
        ),
    ]
