# Generated by Django 3.0.3 on 2020-03-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posapp', '0013_tilledit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.UnitGroup'),
        ),
    ]
