# Generated by Django 3.0.3 on 2020-03-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0014_auto_20200224_1914'),
        ('posapp', '0014_auto_20200303_1640'),
    ]

    operations = [
    ]
