# Generated by Django 3.0.3 on 2020-03-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0015_merge_20200307_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
