# Generated by Django 3.0.3 on 2020-03-12 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0016_product_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productintab',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
