# Generated by Django 3.0.4 on 2020-03-21 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0018_item_allows_fractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productintab',
            name='voidedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productintab',
            name='state',
            field=models.CharField(choices=[('O', 'Ordered'), ('P', 'Being prepared'), ('T', 'To be served'), ('S', 'Served'), ('V', 'Voided')], default='O', max_length=1),
        ),
        migrations.CreateModel(
            name='OrderVoidRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.CharField(blank=True, choices=[('A', 'Approved'), ('D', 'Denied')], max_length=1, null=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voids_approved', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.ProductInTab')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voids_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
