# Generated by Django 3.0.4 on 2020-04-17 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('posapp', '0019_auto_20200321_1648'), ('posapp', '0020_auto_20200321_1652'), ('posapp', '0021_auto_20200416_1927'), ('posapp', '0022_auto_20200416_1956'), ('posapp', '0023_auto_20200416_2002'), ('posapp', '0024_auto_20200417_1036')]

    dependencies = [
        ('posapp', '0018_item_allows_fractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productintab',
            name='voidedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productintab',
            name='state',
            field=models.CharField(choices=[('O', 'Ordered'), ('P', 'Being prepared'), ('T', 'To be served'), ('S', 'Served'), ('V', 'Voided')], default='O', max_length=1),
        ),
        migrations.RenameField(
            model_name='productintab',
            old_name='price',
            new_name='_price',
        ),
        migrations.CreateModel(
            name='OrderVoidRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requestedAt', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.CharField(blank=True, choices=[('A', 'Approved'), ('R', 'Rejected')], max_length=1, null=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voids_approved', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.ProductInTab')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voids_requested', to=settings.AUTH_USER_MODEL)),
                ('resolvedAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='productintab',
            name='_price',
            field=models.DecimalField(db_column='price', decimal_places=3, max_digits=15),
        ),
    ]
