# Generated by Django 3.0.4 on 2020-03-13 14:17

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0018_item_allows_fractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=16),
        ),
    ]
