# Generated by Django 3.0.4 on 2020-03-21 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0019_auto_20200321_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordervoidrequest',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voids_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
