# Generated by Django 3.0.4 on 2020-03-13 14:20
import pyotp
from django.db import migrations

from posapp.models import User


def reset_totp(apps, schema_editor):
    for user in User.objects.all():
        user.totp_secret = pyotp.random_base32()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0019_user_totp_secret'),
    ]

    operations = [
        migrations.RunPython(reset_totp),
    ]
