# Generated by Django 3.0.4 on 2020-04-19 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0020_paymentmethod__enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_director',
        ),
    ]
