# Generated by Django 3.0.4 on 2020-04-16 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0021_auto_20200416_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordervoidrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posapp.ProductInTab'),
        ),
    ]
