# Generated by Django 3.0.4 on 2020-04-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0022_auto_20200416_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordervoidrequest',
            old_name='timestamp',
            new_name='requestedAt',
        ),
        migrations.AddField(
            model_name='ordervoidrequest',
            name='resolvedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
