# Generated by Django 3.0.4 on 2020-04-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0023_auto_20200416_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productintab',
            old_name='price',
            new_name='_price',
        ),
        migrations.AlterField(
            model_name='ordervoidrequest',
            name='resolution',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('R', 'Rejected')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='productintab',
            name='_price',
            field=models.DecimalField(db_column='price', decimal_places=3, max_digits=15),
        ),
    ]
