# Generated by Django 3.0.5 on 2020-04-21 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0024_auto_20200419_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_counter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
