# Generated by Django 3.0.5 on 2020-04-24 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0025_user_online_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='till',
            name='deposit',
            field=models.CharField(default='Unknown', max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='online_counter',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
