# Generated by Django 3.0.5 on 2020-04-28 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posapp', '0025_user_online_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tillpaymentoptions',
            name='depositAmount',
            field=models.DecimalField(decimal_places=3, max_digits=15,
                                      validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
