# Generated by Django 3.0.5 on 2020-04-28 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0026_auto_20200424_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_temp_tab',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_tab_owner', to='posapp.Tab'),
        ),
    ]
