# Generated by Django 3.0.5 on 2020-05-02 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import posapp.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0027_auto_20200428_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('invoice_file', models.FileField(upload_to=posapp.models.generate_expense_upload_to_filename)),
                ('state', django_fsm.FSMField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('rejected', 'Paid')], default='requested', max_length=50, protected=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
