# Generated by Django 3.0.5 on 2020-04-28 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posapp', '0027_auto_20200428_2158'),
        ('posapp', '0026_auto_20200424_1815'),
    ]

    operations = [
    ]
