# Generated by Django 3.0.5 on 2020-04-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0027_auto_20200428_1801'),
        ('posapp', '0028_merge_20200428_2206'),
    ]

    operations = [
    ]
