# Generated by Django 3.0.5 on 2020-05-05 18:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import posapp.models
import uuid


class Migration(migrations.Migration):

    replaces = [('posapp', '0028_expense'), ('posapp', '0031_auto_20200504_1349'), ('posapp', '0032_auto_20200504_1727'), ('posapp', '0033_expense_state_sort')]

    dependencies = [
        ('posapp', '0029_merge_20200429_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to=posapp.models.generate_expense_upload_to_filename)),
                ('state', django_fsm.FSMField(choices=[('new', 'New'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('appealed', 'Appealed'), ('paid', 'Paid')], default='new', max_length=50, protected=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_requested', to=settings.AUTH_USER_MODEL)),
                ('state_sort', models.IntegerField(default=0)),
            ],
        ),
    ]
