# Generated by Django 3.0.5 on 2020-05-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0029_merge_20200429_2027'),
        ('posapp', '0028_expense'),
    ]

    operations = [
    ]
