# Generated by Django 3.0.5 on 2020-05-04 13:49

import django.core.validators
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0030_merge_20200503_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='state',
            field=django_fsm.FSMField(choices=[('new', 'New'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('appealed', 'Appealed'), ('paid', 'Paid')], default='new', max_length=50, protected=True),
        ),
    ]
