# Generated by Django 3.0.7 on 2020-07-01 19:33

from django.db import migrations, models
import django_fsm
import phonenumber_field.modelfields
import posapp.models
import uuid


class Migration(migrations.Migration):

    replaces = [('posapp', '0031_member'), ('posapp', '0032_member_created_at')]

    dependencies = [
        ('posapp', '0030_expense_squashed_0033_expense_state_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('application_file', models.FileField(upload_to=posapp.models.generate_member_application_upload_to_filename)),
                ('membership_status', django_fsm.FSMField(choices=[('new', 'New'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='new', max_length=50, protected=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            bases=(posapp.models.HasActionsMixin, django_fsm.ConcurrentTransitionMixin, models.Model),
        ),
    ]
