# Generated by Django 3.0.5 on 2020-05-04 17:27

from django.db import migrations, models
import posapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0031_auto_20200504_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to=posapp.models.generate_expense_upload_to_filename),
        ),
    ]
