# Generated by Django 3.0.7 on 2020-07-29 18:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0032_auto_20200704_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='_amount',
            new_name='own_amount',
        ),
        migrations.RenameField(
            model_name='tillmoneycount',
            old_name='_amount',
            new_name='own_amount',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='changeMethod',
            field=models.ForeignKey(limit_choices_to={'account__currency__enabled': True, 'changeAllowed': True}, on_delete=django.db.models.deletion.PROTECT, related_name='optionsAsChange', to='posapp.PaymentMethod'),
        ),
    ]
