# Generated by Django 3.0.5 on 2020-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0032_auto_20200504_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='state_sort',
            field=models.IntegerField(default=0),
        ),
    ]
